/******************************************************************************
*	OurOS V 0.0.0 - Copyright (C) 2016
*  Computer and systems department
*  Ain Shams University
*
*  All rights reserved
*
*  VISIT http://www.OurRTOS.org TO ENSURE YOU ARE USING THE LATEST VERSION.
*
*  Redistribution and use in source and binary forms, with or without
*  modification, are permitted provided that the following conditions
*  are met:
*
*  Redistributions of source code must retain the above copyright
*  notice, this list of conditions and the following disclaimer.
*
*  Redistributions in binary form must reproduce the above copyright
*  notice, this list of conditions and the following disclaimer in the
*  documentation and/or other materials provided with the
*  distribution.
*****************************************************************************/

#include "Initialize.h"

struct procent proctab[NPROC];		  /* table of processes */
struct qentry queuetab[NQENT];        /* Table of process queues */
volatile uint8_t* pxCurrentTCB_H;
volatile uint8_t* pxCurrentTCB_L;
/******************************************************************************
*
*	The function's purpose is to initialie the operating system
*
* 	\return none
*
*****************************************************************************/
void initializeOS(void)
{
	clkinit();
}
portSTACK_TYPE *InitialiseStack( portSTACK_TYPE *saddr, pdTASK_CODE pxCode)
{
	//Initialize stack [fady edit]
	
	uint16_t usAddress;

	/* Place a few bytes of known values on the bottom of the stack. 
	This is just useful for debugging. */

	*saddr = 0x0011;
	saddr--;
	*saddr = 0x0022;
	saddr--;
	*saddr = 0x0033;
	saddr--;

	/* Simulate how the stack would look after a call to vPortYield() generated by 
	the compiler. */

	/*lint -e950 -e611 -e923 Lint doesn't like this much - but nothing I can do about it. */

	/* The start of the task code will be popped off the stack last, so place
	it on first. */
	usAddress = ( uint16_t ) pxCode;
	//*saddr = ( char ) ( usAddress & ( uint16_t ) 0x00ff );
	//saddr--;
	*saddr = usAddress;

	//usAddress >>= 8;
	//*saddr = ( char ) ( usAddress & ( uint16_t ) 0x00ff );
	saddr--;

	/* Next simulate the stack as if after a call to portSAVE_CONTEXT().  
	portSAVE_CONTEXT places the flags on the stack immediately after r0
	to ensure the interrupts get disabled as soon as possible, and so ensuring
	the stack use is minimal should a context switch interrupt occur. */
	*saddr = ( uint16_t ) 0x00;	/* R0 */
	saddr--;
	*saddr = portFLAGS_INT_ENABLED;
	saddr--;


	/* Now the remaining registers.   The compiler expects R1 to be 0. */
	*saddr = ( uint16_t ) 0x00;	/* R1 */
	saddr--;
	*saddr = ( uint16_t ) 0x02;	/* R2 */
	saddr--;
	*saddr = ( uint16_t ) 0x03;	/* R3 */
	saddr--;
	*saddr = ( uint16_t ) 0x04;	/* R4 */
	saddr--;
	*saddr = ( uint16_t ) 0x05;	/* R5 */
	saddr--;
	*saddr = ( uint16_t ) 0x06;	/* R6 */
	saddr--;
	*saddr = ( uint16_t ) 0x07;	/* R7 */
	saddr--;
	*saddr = ( uint16_t ) 0x08;	/* R8 */
	saddr--;
	*saddr = ( uint16_t ) 0x09;	/* R9 */
	saddr--;
	*saddr = ( uint16_t ) 0x10;	/* R10 */
	saddr--;
	*saddr = ( uint16_t ) 0x11;	/* R11 */
	saddr--;
	*saddr = ( uint16_t ) 0x12;	/* R12 */
	saddr--;
	*saddr = ( uint16_t ) 0x13;	/* R13 */
	saddr--;
	*saddr = ( uint16_t ) 0x14;	/* R14 */
	saddr--;
	*saddr = ( uint16_t ) 0x15;	/* R15 */
	saddr--;
	*saddr = ( uint16_t ) 0x16;	/* R16 */
	saddr--;
	*saddr = ( uint16_t ) 0x17;	/* R17 */
	saddr--;
	*saddr = ( uint16_t ) 0x18;	/* R18 */
	saddr--;
	*saddr = ( uint16_t ) 0x19;	/* R19 */
	saddr--;
	*saddr = ( uint16_t ) 0x20;	/* R20 */
	saddr--;
	*saddr = ( uint16_t ) 0x21;	/* R21 */
	saddr--;
	*saddr = ( uint16_t ) 0x22;	/* R22 */
	saddr--;
	*saddr = ( uint16_t ) 0x23;	/* R23 */
	saddr--;

	///* Place the parameter on the stack in the expected location. */
	//usAddress = ( uint16_t ) pvParameters;
	//*saddr = ( uint16_t ) ( usAddress & ( uint16_t ) 0x00ff );
	//saddr--;
//
	//usAddress >>= 8;
	//*saddr = ( uint16_t ) ( usAddress & ( uint16_t ) 0x00ff );
	//saddr--;

	*saddr = ( uint16_t ) 0x26;	/* R26 X */
	saddr--;
	*saddr = ( uint16_t ) 0x27;	/* R27 */
	saddr--;
	*saddr = ( uint16_t ) 0x28;	/* R28 Y */
	saddr--;
	*saddr = ( uint16_t ) 0x29;	/* R29 */
	saddr--;
	*saddr = ( uint16_t ) 0x30;	/* R30 Z */
	saddr--;
	*saddr = ( uint16_t ) 0x031;	/* R31 */
	saddr--;
	return saddr;
}
