
#ifndef TIMERCOUNTER0_CFG_H_
#define TIMERCOUNTER0_CFG_H_

#define PRESCALAR_NUM 5

#define u8_MODE_NORMAL 0x00
#define u8_MODE_CTC 0x02

#define COM01_VALUE 0
#define COM00_VALUE 0

#endif /* TIMERCOUNTER0_CFG_H_ */